hw1_r:
	gcc -Wall -ansi -pedantic-errors hw1_recursive.c -o hw1_r

hw1_i:
	gcc -Wall -ansi -pedantic-errors hw1_iterative.c -o hw1_i -lm

hwi:
	gcc -Wall -ansi -pedantic-errors hwi.c -o hwi

clean:
	rm -f hw1_r hw1_i hwi
